---
apiVersion: networking.k8s.io/v1
kind: Ingress #Ingress is outside of cluster, routing request from client to exactly service we define in above.
metadata:
  name: web-demo-ingress
  namespace: space2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: "/web"
        pathType: Prefix
        backend:
          service:
            name: web-demo-service
            port: 
              number: 80
      # - path: /mysql
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: mysql-service
      #       port: 
      #         number: 3306